sudo: required
dist: trusty
language: java
dist: trusty
jdk: oraclejdk8
addons:
  ssh_known_hosts:
  - 47.93.42.145:22008
  - 47.93.42.145:22008
  - 47.93.42.145:22008
  - 47.93.18.60:22008
  - 47.93.18.60:22008
  - 47.93.18.60:22008
  sonarcloud:
    organization: tron-zhaohong
    token:
      secure: "KXWEeQ1elAoQ0XfR54TQWfhrIdDP0+2CYPv2X9aWpU/YDl7hqZBAjcCOAUGvlbyM54jtG6YMaWwG48jlrOwwl5l/VjWSnUXF+7ixQy5ki0Ci9s7Y1pTQwV9SpL8TLIK2TYqabN8Mw+FJULASXLjYr9GerbbcUbCPTmcL6mQKw6ivxxpNPmz4eNoKAEuOzruO9fTXGAV3yr8Nn85c+mVxV8EUhkR17zpE9O8fvzOtSnYArWNOSCgDBn0EG45UNNPF2vn44s1c3h3gX1m3WK6PeCXPgy3hPqRn3wTG+xglnbqthGpo2wt1rJ83af+BwdYwvPEcUq84yLgXcE/aMkTKcVAfPWBP/6vblaoI90jxCeFji+MdMimKZAqIXt7oLqDZVmIq65de5YC5s7QTSbzJNY/tsAu3dqzSfbUJY6CRNFDcoenVpvgQkqb37TkDah4mJM8EUjbu2A9Q2HSFbyCVsQJtdasuu9cBOf6azK3U0XgFNBc0y2aziZrTnX30q7bi+5L/mbTnRdXrDqBOqyPeGtT77UZfcajHHmEWU/e6gYWiA/c+K25n13DD53Au6gpnnQ6ALeUl/1gDwz3fPBebJ5bVWrkIcLj7bbysjzfOvQmDS6G13RNz58Hm0/B7bVtZTr1E1q6Z1zEJwbuJYEJASNcezAfK5x/hIfZTGNqT3M8="
cache:
  directories:
  - '$HOME/.sonar/cache'
matrix:
  include:
    - name: build
      script:
        - sh tron.sh
        - "./gradlew build"
        - "./gradlew jacocoTestReport"


    - name: stest
      script:
        - sh tron.sh
        - bash deploy.sh


after_success:
  - "bash <(curl -s https://codecov.io/bash) -t $codecov_token_key -s build/reports/jacoco/"

skip_build:
  - README.md：
  - LICENSE


notifications:
  slack:
    secure: Th47xL+wz7BDGHy3VyWXvAiaumVprvcPjQvqJJ/Zs+xdubqEl2aFQ0G2mr1OcjTYwDgHTNVwT00w4qgyF8r/boEL9EcxYXSLj4p+ZxLNjisJRNTF7KUmMcFVowgeNRyFPOYv4qkcgB5sug5W0vfksbdih7CJGSVP7FCJH/SgB0aYwy6Usfg1IfWkZo0I3Cgkhdlz0dgQMc0s/lzVVlJHlIbfmPLwBgNhfyzwZhpgOEXbfJfvUC43zun5EUKqn9T/WMG/eS/yx6jkSB+di/ftyyLNtXAzZP9gl5M/5z2hoCqYC6JDOWVP4kGGxmfzZ6DdapfZJWjxeU4xitkq2/fqH4vOfE2AUxyedyNu04mS66YxqV7NcdNtv6p3oCcbIRa9R80jjsX0hrP+/h9BjTsZld5ht23MddClPMtq4qaxWFiztzJGv4kzsmHy9TNRZK6HATXQr52go6JROEI8TYt4unFkcQeV6OEBiV4LNSrZuY+lth/flg2nFSrLxIPzNpHPVL8r7TxNRxv4pPHazlDF+VWlLCHAlj/Rcmh8HYMRm3KJCD4tmoi64+/n50HRJyNSpFuZVXWUJEiHMtRUu0h5uU98jwLweusEVCGpb6QBxY0oMPiiz91wzQEtpxrCtznvQj8jmzNyaXrHIg2RypuyReX72WlGkdJzevavEJ2JWTw=
  if: branch = master || develop 


